package initialize

import (
	"os"

	"gitlab.com/ucard/global"
	"gitlab.com/ucard/model/client"
	"gitlab.com/ucard/model/common"
	"gitlab.com/ucard/model/finance"
	"gitlab.com/ucard/model/system"

	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Gorm 初始化数据库并产生数据库全局变量
// Author SliverHorn
func Gorm() *gorm.DB {
	switch global.GVA_CONFIG.System.DbType {
	case "mysql":
		return GormMysql()
	case "pgsql":
		return GormPgSql()
	default:
		return GormMysql()
	}
}

// RegisterTables 注册数据库表专用
// Author SliverHorn
func RegisterTables(db *gorm.DB) {
	err := db.AutoMigrate(
		// 系统模块表
		system.SysApi{},
		system.SysUser{},
		system.SysBaseMenu{},
		system.JwtBlacklist{},
		system.SysAuthority{},
		system.SysOperationRecord{},
		system.SysBaseMenuParameter{},
		system.SysBaseMenuBtn{},
		system.SysAuthorityBtn{},

		// 自动化模块表
		// Code generated by gitlab.com/ucard Begin; DO NOT EDIT.
		client.Client{},
		client.ClientDueDiligence{},
		client.Wallet{},
		client.SessionLog{},
		client.ClientPermission{},
		client.ClientAccountPermission{},
		client.ClientRole{},
		client.IAMUser{},
		client.IAMRole{},
		client.IAMPermission{},

		finance.WalletHistory{},
		finance.WalletRecharge{},
		finance.CardBin{},
		finance.CardHolder{},
		finance.PixielCard{},
		finance.WalletWithdraw{},
		finance.ClientDailyReport{},

		finance.CardTransactionRecord{},

		finance.FeeGlobalConfig{},
		finance.FeeUserConfig{},
		finance.FeeDetail{},
		finance.CardGroup{},
		common.OpLog{},
		common.AdminConfig{},
		common.SmsCode{},
		// Code generated by gitlab.com/ucard End; DO NOT EDIT.

		//红人艺术家模块
	)
	if err != nil {
		global.GVA_LOG.Error("register table failed", zap.Error(err))
		os.Exit(0)
	}
	global.GVA_LOG.Info("register table success")
}
